### ISSUE TITLE
Caption below  figure not visible

### ISSUE THREAD

**Issue by solosTec** [usamamuneeb/uic-beamer-template#1]
In a frame section that follows a chapter section the caption below a figure is not visible.

```
\begin{chapter}[]{}{CHAPTER}
\end{chapter}

\begin{frame}{FRAME}
  \begin{figure}
  ...
  \caption{CAPTION}% not visible
  \end{figure}
\end{frame}

```

**Comment by usamamuneeb** [comment]
Thank you for pointing it out! I was able to reproduce it as well. The solution is to insert `\usebeamercolor[fg]{normal text}` between the chapter slide and the slide with the captioned figure, like this:

```tex
\end{chapter}
\usebeamercolor[fg]{normal text}
\begin{frame}{FRAME}
```

I'm not sure why this happens. This is the same issue mentioned on the slide talking about switching themes in the middle of the presentation. I am yet to investigate it properly, and hopefully the proper fix will also solve the problem when it happens due to theme switching.

**Comment by usamamuneeb** [comment]
I modified the style file to automatically do what I had suggested above and that seems to solve the problem. Thanks again for pointing this out!
